//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstateAgent
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealEstateFilterSet
    {
        public int Id { get; set; }
    
        public virtual DemandSet DemandSet { get; set; }
        public virtual RealEstateFilterSet_ApartmentFilter RealEstateFilterSet_ApartmentFilter { get; set; }
        public virtual RealEstateFilterSet_HouseFilter RealEstateFilterSet_HouseFilter { get; set; }
        public virtual RealEstateFilterSet_LandFilter RealEstateFilterSet_LandFilter { get; set; }
    }
}
